package miEmpresa;
// Generated 7 ene 2024, 22:02:49 by Hibernate Tools 6.3.1.Final

/**
 * Productos generated by hbm2java
 */
public class Productos implements java.io.Serializable {

	private Integer id;
	private String nombre;
	private Double precio;

	public Productos() {
	}

	public Productos(String nombre, Double precio) {
		this.nombre = nombre;
		this.precio = precio;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Double getPrecio() {
		return this.precio;
	}

	public void setPrecio(Double precio) {
		this.precio = precio;
	}

}
